<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 23:00:02
?>
<?php use_helper('Object') ?>

<?php echo form_tag('user/update') ?>

<?php echo object_input_hidden_tag($user, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Email*:</th>
  <td><?php echo object_input_tag($user, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Display name*:</th>
  <td><?php echo object_input_tag($user, 'getDisplayName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Authenticated*:</th>
  <td><?php echo object_input_tag($user, 'getAuthenticated', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Deleted*:</th>
  <td><?php echo object_input_tag($user, 'getDeleted', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Newsletter subscribe*:</th>
  <td><?php echo object_input_tag($user, 'getNewsletterSubscribe', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Dob:</th>
  <td><?php echo object_input_date_tag($user, 'getDob', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Gender:</th>
  <td><?php echo object_input_tag($user, 'getGender', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Country:</th>
  <td><?php echo object_input_tag($user, 'getCountry', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Profile:</th>
  <td><?php echo object_textarea_tag($user, 'getProfile', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>First name:</th>
  <td><?php echo object_input_tag($user, 'getFirstName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Last name:</th>
  <td><?php echo object_input_tag($user, 'getLastName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Zip code:</th>
  <td><?php echo object_input_tag($user, 'getZipCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>State:</th>
  <td><?php echo object_input_tag($user, 'getState', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>City:</th>
  <td><?php echo object_input_tag($user, 'getCity', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Password hash*:</th>
  <td><?php echo object_input_tag($user, 'getPasswordHash', array (
  'size' => 32,
)) ?></td>
</tr>
<tr>
  <th>Profile private:</th>
  <td><?php echo object_input_tag($user, 'getProfilePrivate', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Personal private:</th>
  <td><?php echo object_input_tag($user, 'getPersonalPrivate', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Image*:</th>
  <td><?php echo object_input_tag($user, 'getImageId', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($user->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'user/delete?id='.$user->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'user/show?id='.$user->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'user/list') ?>
<?php endif; ?>
</form>
