<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 23:00:02
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $user->getEmail() ?></td>
</tr>
<tr>
<th>Display name: </th>
<td><?php echo $user->getDisplayName() ?></td>
</tr>
<tr>
<th>Authenticated: </th>
<td><?php echo $user->getAuthenticated() ?></td>
</tr>
<tr>
<th>Deleted: </th>
<td><?php echo $user->getDeleted() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $user->getUpdatedAt() ?></td>
</tr>
<tr>
<th>Newsletter subscribe: </th>
<td><?php echo $user->getNewsletterSubscribe() ?></td>
</tr>
<tr>
<th>Dob: </th>
<td><?php echo $user->getDob() ?></td>
</tr>
<tr>
<th>Gender: </th>
<td><?php echo $user->getGender() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $user->getCountry() ?></td>
</tr>
<tr>
<th>Profile: </th>
<td><?php echo $user->getProfile() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $user->getFirstName() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $user->getLastName() ?></td>
</tr>
<tr>
<th>Zip code: </th>
<td><?php echo $user->getZipCode() ?></td>
</tr>
<tr>
<th>State: </th>
<td><?php echo $user->getState() ?></td>
</tr>
<tr>
<th>City: </th>
<td><?php echo $user->getCity() ?></td>
</tr>
<tr>
<th>Password hash: </th>
<td><?php echo $user->getPasswordHash() ?></td>
</tr>
<tr>
<th>Profile private: </th>
<td><?php echo $user->getProfilePrivate() ?></td>
</tr>
<tr>
<th>Personal private: </th>
<td><?php echo $user->getPersonalPrivate() ?></td>
</tr>
<tr>
<th>Image: </th>
<td><?php echo $user->getImageId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'user/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'user/list') ?>
