<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 22:59:45
?>
<h1>category</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Parent category</th>
  <th>Name</th>
  <th>Slug</th>
  <th>Listed</th>
</tr>
</thead>
<tbody>
<?php foreach ($categorys as $category): ?>
<tr>
    <td><?php echo link_to($category->getId(), 'category/show?id='.$category->getId()) ?></td>
      <td><?php echo $category->getParentCategoryId() ?></td>
      <td><?php echo $category->getName() ?></td>
      <td><?php echo $category->getSlug() ?></td>
      <td><?php echo $category->getListed() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'category/create') ?>
