<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 22:59:45
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $category->getId() ?></td>
</tr>
<tr>
<th>Parent category: </th>
<td><?php echo $category->getParentCategoryId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $category->getName() ?></td>
</tr>
<tr>
<th>Slug: </th>
<td><?php echo $category->getSlug() ?></td>
</tr>
<tr>
<th>Listed: </th>
<td><?php echo $category->getListed() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'category/edit?id='.$category->getId()) ?>
&nbsp;<?php echo link_to('list', 'category/list') ?>
