<?php
// auto-generated by sfPropelCrud
// date: 2007/08/19 16:25:57
?>
<?php use_helper('Object') ?>

<?php echo form_tag('item/update') ?>

<?php echo object_input_hidden_tag($item, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Quote:</th>
  <td><?php echo object_textarea_tag($item, 'getText', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Date:</th>
  <td><?php echo object_input_date_tag($item, 'getDate', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Person:</th>
  <td><?php echo object_select_tag($item, 'getCreatorId', array (
  'related_class' => 'Creator',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Category:</th>
  <td><?php echo object_select_tag($item, 'getCategoryId', array (
  'related_class' => 'Category',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Tags:</th>
  <td><?php echo input_tag('tags', implode(', ', $item->getTags())); ?></td>
</tr>
</tbody>
</table>
<hr />

<hr />
<?php echo submit_tag('save') ?>
<?php if ($item->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'item/delete?id='.$item->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'item/show?id='.$item->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'item/list') ?>
<?php endif; ?>
</form>
