<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 22:59:53
?>
<?php use_helper('Object') ?>

<ul class="crumbtrail">
	<li><?php echo link_to('Home', 'default/index'); ?></li>
	<?php if ($item): ?>
		<li><?php echo link_to('Authors', 'creator/list?letter=A'); ?></li>
		<?php if($creator = $item->getCreator()): ?>
			<li><?php echo link_to($creator->getName(), 'creator/show?slug=' . $creator->getSlug()); ?></li>
		<?php endif; ?>
		<li><?php echo link_to(truncate_text(strip_tags($item->getText()), 20), 'item/show?slug='.$item->getSlug()); ?></li>
	<?php endif; ?>
	<li>Comment</li>
</ul>


<?php include_partial('global/box_top'); ?>
	<h1>Permission Denied</h1>
	<p>Sorry, you are not allowed to edit or delete this comment. You may only edit a comment up to one hour after submitting it. </p>
	<?php if ($item): ?>
		<?php echo link_to('Back to Quote', 'item/show?slug='.$item->getSlug()) ?>
	<?php endif; ?>
<?php include_partial('global/box_bottom'); ?>