<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 22:59:53
?>
<?php use_helper('Object') ?>

<?php use_helper('Text'); ?>
<ul class="crumbtrail">
	<li><?php echo link_to('Home', 'default/index'); ?></li>
	<?php if ($item = $comment->getItem()): ?>
		<li><?php echo link_to('Authors', 'creator/list?letter=A'); ?></li>
		<?php if($creator = $item->getCreator()): ?>
			<li><?php echo link_to($creator->getName(), 'creator/show?slug=' . $creator->getSlug()); ?></li>
		<?php endif; ?>
		<li><?php echo link_to(truncate_text(strip_tags($item->getText()), 20), 'item/show?slug='.$item->getSlug()); ?></li>
	<?php endif; ?>
	<li>Edit Comment</li>
</ul>

<?php use_helper('Validation') ?>
<?php include_partial('global/box_top'); ?>
	<h1>Edit Comment</h1>
	<?php echo form_tag('comment/update', array('class' => 'comment')) ?>
		<?php if ($item): ?>
			<?php echo input_hidden_tag('item_slug', $item->getSlug()) ?>
		<?php endif; ?>
		<?php if ($comment->getId()): ?>
			<?php echo object_input_hidden_tag($comment, 'getId') ?>
		<?php endif; ?>
		
		<label for="user_name">Name (required)<label><br />
		<?php echo form_error('user_name') ?>
		<?php echo object_input_tag($comment, 'getUserName'); ?><br /><br />

		<label for="text">Your Comment (required)</label><br />
		<?php echo form_error('text') ?>
		<?php echo object_textarea_tag($comment, 'getText'); ?><br /><br />

		<?php echo submit_tag('Save Comment') ?>
		<?php if ($item = $comment->getItem()): ?>
			<?php echo link_to('Cancel', 'item/show?slug='.$item->getSlug()) ?>
		<?php endif; ?>
	</form>
<?php include_partial('global/box_bottom'); ?>
