<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 23:00:15
?>
<?php

/**
 * tag actions.
 *
 * @package    quotes
 * @subpackage tag
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class tagActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('tag', 'list');
  }

  public function executeList()
  {
      $this->tags = TagPeer::getPopular(200);
	TitleHelper::setTitle('Browse Tags');
  }

  public function executeShow()
  {
    $this->tag = TagPeer::retrieveByName($this->getRequestParameter('name'));
    $this->forward404Unless($this->tag);
	TitleHelper::setTitle(sprintf('Quotes Tagged "%s"',  $this->tag));
	
	$this->pager = new sfPropelPager('Item', 25);
    $this->pager->setCriteria($this->tag->getItemsCriteria());
    $this->pager->setPage($this->getRequestParameter('page', 1));
    $this->pager->init();
  }
}
