<?php
// auto-generated by sfPropelCrud
// date: 2007/08/18 23:00:33
?>
<?php

/**
 * creator actions.
 *
 * @package		quotes
 * @subpackage creator
 * @author		 Your name here
 * @version		SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class creatorActions extends sfActions
{
	public function executeIndex()
	{
		return $this->forward('creator', 'list');
	}

	public function executeList()
	{
		$this->letter = $this->getRequestParameter('letter');
		$this->forward404Unless($this->letter >= 'A' && $this->letter <= 'Z');
		$this->creators = CreatorPeer::doSelect(CreatorPeer::getListCriteria($this->letter));
		TitleHelper::setTitle('Browse Authors');
	}

	public function executeShow()
	{
		$this->creator = CreatorPeer::retrieveBySlug($this->getRequestParameter('slug'));
		$this->forward404Unless($this->creator);
		TitleHelper::setTitle(sprintf('%s Quotes', $this->creator->getName()));

		$this->pager = new sfPropelPager('Item', 25);
		$this->pager->setCriteria($this->creator->getItemsCriteria());
	    $this->pager->setPage($this->getRequestParameter('page', 1));
	    $this->pager->init();
	}
}
